/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "count": string;
    }
    interface SaboteurBoard {
        /**
          * The first name
         */
        "count": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSaboteurBoardElement extends Components.SaboteurBoard, HTMLStencilElement {
    }
    var HTMLSaboteurBoardElement: {
        prototype: HTMLSaboteurBoardElement;
        new (): HTMLSaboteurBoardElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "saboteur-board": HTMLSaboteurBoardElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "count"?: string;
    }
    interface SaboteurBoard {
        /**
          * The first name
         */
        "count"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "saboteur-board": SaboteurBoard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "saboteur-board": LocalJSX.SaboteurBoard & JSXBase.HTMLAttributes<HTMLSaboteurBoardElement>;
        }
    }
}
